name: test api

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  boost-install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 21, 22, 23, 24, 25]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean and Install
        run: |
          npm cache clean --force
          npm install api-qasim --no-save
